title = "Biometry Hub Internship"
baseURL = "https://biometryhubinterns.netlify.app/"
theme = "bilberry-hugo-theme"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
# disqusShortname = ""

# Enable / Disable open link with a new tab.
[blackfriday]
  hrefTargetBlank = false
  
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = ["custom.css"]
  js_modules = []

  # Description and meta data for the search engines
  author = "Biometry Interns"
  description = "Website for biomtery hub interns."
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "JEM5B6WHHX"
  algolia_apiKey    = "e00fe80e07e3f51c3a30e4d3b389b93e"
  algolia_indexName = "default-content"
    # Set this option to false if you want to search within all articles in all languages at once
    algolia_currentLanguageOnly = true

  # Enable / Disable comments on the articles via commento
  commentoJsURL = "https://commento.lednerb.de/js/commento.js"

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = false

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "School of Agriculture, Food and Wine, University of Adelaide, Australia"

    # if you want to use gravatar for the header image
    gravatarEMail = "featuredImage.png"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "gravatar.jpg"

    # define the icon you want to use for the overlay for the customImage or gravatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = false

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "/content/github/"
    # Set to true to pin only to the first page, false to all pages
    # pinOnlyToFirstPage = true

    # enable automatical localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "02-01-2006"

    # display the estimated reading time for an article
    showReadingTime = false

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 7

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 7

    # show a language chooser in the footer
    showFooterLanguageChooser = false

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://twitter.com/SAGISouth", icon = "fab fa-twitter" },
      { link = "https://github.com/biometryhub", icon = "fab fa-github" },
      # { link = "biometryhub@adelaide.edu.au", icon = "fas fa-inbox"},
      # { link = "+61 8 8313 2246", icon = "fas fa-phone-alt"}
    ]

    # credits line configuration
    copyrightBy = "Biometry Hub"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2017"
    copyrightUrl = "https://sciences.adelaide.edu.au/agriculture-food-wine/research/agricultural-science/biometry-hub"
    creditsText = "Biometry Hub Internship"
    creditsUrl = "https://github.com/biometryhub"


# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1
  #[Languages.de]
   # weight = 0
    #title = "Mein cooler neuer Blog"
    #subtitle = "Hallo Welt! Dies ist der epischste Untertitel aller Zeiten."

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]

